apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.sample.dev
spec:
  group: sample.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
                count:
                  type: integer
                  minimum: 1
                  maximum: 10
  names:
    kind: Foo
    plural: foos
  scope: Namespaced
